// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package codegen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	Access_tokenScopes = "access_token.Scopes"
)

// Defines values for YSKCardCardType.
const (
	YSKCardCardTypeLongNotice  YSKCardCardType = "long-notice"
	YSKCardCardTypeShortNotice YSKCardCardType = "short-notice"
	YSKCardCardTypeTask        YSKCardCardType = "task"
)

// Defines values for YSKCardRenderType.
const (
	YSKCardRenderTypeIconTextNotice YSKCardRenderType = "icon-text-notice"
	YSKCardRenderTypeListNotice     YSKCardRenderType = "list-notice"
	YSKCardRenderTypeMarkdownNotice YSKCardRenderType = "markdown-notice"
	YSKCardRenderTypeTask           YSKCardRenderType = "task"
)

// Action defines model for Action.
type Action struct {
	// Name action name
	Name string `json:"name"`

	// Properties event properties
	Properties map[string]string `json:"properties"`

	// SourceID associated source id
	SourceID string `json:"sourceID"`

	// Timestamp timestamp this action took place
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// ActionType defines model for ActionType.
type ActionType struct {
	// Name action name
	//
	// (there is no naming convention for action names, but it is recommended to name each as structural and descriptive as possible)
	Name             string         `json:"name"`
	PropertyTypeList []PropertyType `json:"propertyTypeList"`

	// SourceID action source id to identify where the action will take
	SourceID string `json:"sourceID"`
}

// BaseResponse defines model for BaseResponse.
type BaseResponse struct {
	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// Event defines model for Event.
type Event struct {
	// Name event name
	Name string `json:"name"`

	// Properties event properties
	Properties map[string]string `json:"properties"`

	// SourceID associated source id
	SourceID string `json:"sourceID"`

	// Timestamp timestamp this event took place
	Timestamp *time.Time `json:"timestamp,omitempty"`

	// Uuid event uuid
	Uuid *string `json:"uuid,omitempty"`
}

// EventType defines model for EventType.
type EventType struct {
	// Name event name
	//
	// (there is no naming convention for event names, but it is recommended to name each as structural and descriptive as possible)
	Name             string         `json:"name"`
	PropertyTypeList []PropertyType `json:"propertyTypeList"`

	// SourceID event source id to identify where the event comes from
	SourceID string `json:"sourceID"`
}

// PropertyType defines model for PropertyType.
type PropertyType struct {
	Description *string `json:"description,omitempty"`
	Example     *string `json:"example,omitempty"`

	// Name property name
	//
	// > It is recommended for a property name to be as descriptive as possible. One option is to prefix with a namespace.
	// > - If the property is source specific, prefix with source ID. For example, `local-storage:vendor`
	// > - Otherwise, prefix with `common:`. For example, `common:email`
	// >
	// > Some bad examples are `id`, `avail`, `blk`...which can be ambiguous and confusing.
	Name string `json:"name"`
}

// YSKCard defines model for YSKCard.
type YSKCard struct {
	CardType   YSKCardCardType   `json:"cardType"`
	Content    YSKCardContent    `json:"content"`
	Id         string            `json:"id"`
	RenderType YSKCardRenderType `json:"renderType"`
}

// YSKCardCardType defines model for YSKCard.CardType.
type YSKCardCardType string

// YSKCardRenderType defines model for YSKCard.RenderType.
type YSKCardRenderType string

// YSKCardContent defines model for YSKCardContent.
type YSKCardContent struct {
	BodyIconWithText *YSKCardIconWithText   `json:"bodyIconWithText,omitempty"`
	BodyList         *[]YSKCardListItem     `json:"bodyList,omitempty"`
	BodyProgress     *YSKCardProgress       `json:"bodyProgress,omitempty"`
	FooterActions    *[]YSKCardFooterAction `json:"footerActions,omitempty"`
	TitleIcon        YSKCardIcon            `json:"titleIcon"`
	TitleText        string                 `json:"titleText"`
}

// YSKCardFooterAction defines model for YSKCardFooterAction.
type YSKCardFooterAction struct {
	MessageBus YSKCardMessageBusAction `json:"messageBus"`
	Side       string                  `json:"side"`
	Style      string                  `json:"style"`
	Text       string                  `json:"text"`
}

// YSKCardIcon defines model for YSKCardIcon.
type YSKCardIcon = string

// YSKCardIconWithText defines model for YSKCardIconWithText.
type YSKCardIconWithText struct {
	Description string      `json:"description"`
	Icon        YSKCardIcon `json:"icon"`
}

// YSKCardList defines model for YSKCardList.
type YSKCardList = []YSKCard

// YSKCardListItem defines model for YSKCardListItem.
type YSKCardListItem struct {
	Description string      `json:"description"`
	Icon        YSKCardIcon `json:"icon"`
	RightText   string      `json:"rightText"`
}

// YSKCardMessageBusAction defines model for YSKCardMessageBusAction.
type YSKCardMessageBusAction struct {
	Key     string `json:"key"`
	Payload string `json:"payload"`
}

// YSKCardProgress defines model for YSKCardProgress.
type YSKCardProgress struct {
	Label    string `json:"label"`
	Progress int    `json:"progress"`
}

// ActionName defines model for ActionName.
type ActionName = string

// ActionNames defines model for ActionNames.
type ActionNames = []string

// EventName defines model for EventName.
type EventName = string

// EventNames defines model for EventNames.
type EventNames = []string

// SourceID defines model for SourceID.
type SourceID = string

// GetActionTypeOK defines model for GetActionTypeOK.
type GetActionTypeOK = ActionType

// GetActionTypesOK defines model for GetActionTypesOK.
type GetActionTypesOK = []ActionType

// GetEventTypeOK defines model for GetEventTypeOK.
type GetEventTypeOK = EventType

// GetEventTypesOK defines model for GetEventTypesOK.
type GetEventTypesOK = []EventType

// PublishEventOK defines model for PublishEventOK.
type PublishEventOK = Event

// ResponseBadRequest defines model for ResponseBadRequest.
type ResponseBadRequest = BaseResponse

// ResponseConflict defines model for ResponseConflict.
type ResponseConflict = BaseResponse

// ResponseForbidden defines model for ResponseForbidden.
type ResponseForbidden = BaseResponse

// ResponseGetYSKCardListOK defines model for ResponseGetYSKCardListOK.
type ResponseGetYSKCardListOK struct {
	Data *YSKCardList `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ResponseInternalServerError defines model for ResponseInternalServerError.
type ResponseInternalServerError = BaseResponse

// ResponseNotFound defines model for ResponseNotFound.
type ResponseNotFound = BaseResponse

// ResponseOK defines model for ResponseOK.
type ResponseOK = BaseResponse

// ResponseTooManyRequests defines model for ResponseTooManyRequests.
type ResponseTooManyRequests = BaseResponse

// TriggerActionOK defines model for TriggerActionOK.
type TriggerActionOK = Action

// PublishEvent event properties
type PublishEvent map[string]string

// RegisterActionTypes defines model for RegisterActionTypes.
type RegisterActionTypes = []ActionType

// RegisterEventTypes defines model for RegisterEventTypes.
type RegisterEventTypes = []EventType

// TriggerAction action properties
type TriggerAction map[string]string

// SubscribeActionWSParams defines parameters for SubscribeActionWS.
type SubscribeActionWSParams struct {
	Names *ActionNames `form:"names,omitempty" json:"names,omitempty"`
}

// TriggerActionJSONBody defines parameters for TriggerAction.
type TriggerActionJSONBody map[string]string

// RegisterActionTypesJSONBody defines parameters for RegisterActionTypes.
type RegisterActionTypesJSONBody = []ActionType

// SubscribeEventWSParams defines parameters for SubscribeEventWS.
type SubscribeEventWSParams struct {
	Names *EventNames `form:"names,omitempty" json:"names,omitempty"`
}

// PublishEventJSONBody defines parameters for PublishEvent.
type PublishEventJSONBody map[string]string

// RegisterEventTypesJSONBody defines parameters for RegisterEventTypes.
type RegisterEventTypesJSONBody = []EventType

// TriggerActionJSONRequestBody defines body for TriggerAction for application/json ContentType.
type TriggerActionJSONRequestBody TriggerActionJSONBody

// RegisterActionTypesJSONRequestBody defines body for RegisterActionTypes for application/json ContentType.
type RegisterActionTypesJSONRequestBody = RegisterActionTypesJSONBody

// PublishEventJSONRequestBody defines body for PublishEvent for application/json ContentType.
type PublishEventJSONRequestBody PublishEventJSONBody

// RegisterEventTypesJSONRequestBody defines body for RegisterEventTypes for application/json ContentType.
type RegisterEventTypesJSONRequestBody = RegisterEventTypesJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Subscribe to actions by source ID (WebSocket)
	// (GET /action/{source_id})
	SubscribeActionWS(ctx echo.Context, sourceId SourceID, params SubscribeActionWSParams) error
	// Trigger an action
	// (POST /action/{source_id}/{name})
	TriggerAction(ctx echo.Context, sourceId SourceID, name ActionName) error
	// List action types
	// (GET /action_type)
	GetActionTypes(ctx echo.Context) error
	// Register one or more action types
	// (POST /action_type)
	RegisterActionTypes(ctx echo.Context) error
	// Get action types by source ID
	// (GET /action_type/{source_id})
	GetActionTypesBySourceID(ctx echo.Context, sourceId SourceID) error
	// Get an action type by source ID and name
	// (GET /action_type/{source_id}/{name})
	GetActionType(ctx echo.Context, sourceId SourceID, name ActionName) error
	// Subscribe to events by source ID (WebSocket)
	// (GET /event/{source_id})
	SubscribeEventWS(ctx echo.Context, sourceId SourceID, params SubscribeEventWSParams) error
	// Publish an event
	// (POST /event/{source_id}/{name})
	PublishEvent(ctx echo.Context, sourceId SourceID, name EventName) error
	// List event types
	// (GET /event_type)
	GetEventTypes(ctx echo.Context) error
	// Register one or more event types
	// (POST /event_type)
	RegisterEventTypes(ctx echo.Context) error
	// Get event types by source ID
	// (GET /event_type/{source_id})
	GetEventTypesBySourceID(ctx echo.Context, sourceId SourceID) error
	// Get an event type by source ID and name
	// (GET /event_type/{source_id}/{name})
	GetEventType(ctx echo.Context, sourceId SourceID, name EventName) error
	// Subscribe to events and actions (SocketIO)
	// (GET /socket.io)
	SubscribeSIO(ctx echo.Context) error
	// Poll events and actions (SocketIO)
	// (POST /socket.io)
	PollSIO(ctx echo.Context) error
	// Subscribe to events and actions (SocketIO)
	// (GET /socket.io/)
	SubscribeSIO2(ctx echo.Context) error
	// Poll events and actions (SocketIO)
	// (POST /socket.io/)
	PollSIO2(ctx echo.Context) error
	// Issue a subscription ticket
	// (POST /ticket)
	IssueSubscriptionTicket(ctx echo.Context) error

	// (GET /ysk)
	GetYskCard(ctx echo.Context) error

	// (DELETE /ysk/{id})
	DeleteYskCard(ctx echo.Context, id string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// SubscribeActionWS converts echo context to params.
func (w *ServerInterfaceWrapper) SubscribeActionWS(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params SubscribeActionWSParams
	// ------------- Optional query parameter "names" -------------

	err = runtime.BindQueryParameter("form", true, false, "names", ctx.QueryParams(), &params.Names)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter names: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SubscribeActionWS(ctx, sourceId, params)
	return err
}

// TriggerAction converts echo context to params.
func (w *ServerInterfaceWrapper) TriggerAction(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name ActionName

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.TriggerAction(ctx, sourceId, name)
	return err
}

// GetActionTypes converts echo context to params.
func (w *ServerInterfaceWrapper) GetActionTypes(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetActionTypes(ctx)
	return err
}

// RegisterActionTypes converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterActionTypes(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RegisterActionTypes(ctx)
	return err
}

// GetActionTypesBySourceID converts echo context to params.
func (w *ServerInterfaceWrapper) GetActionTypesBySourceID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetActionTypesBySourceID(ctx, sourceId)
	return err
}

// GetActionType converts echo context to params.
func (w *ServerInterfaceWrapper) GetActionType(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name ActionName

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetActionType(ctx, sourceId, name)
	return err
}

// SubscribeEventWS converts echo context to params.
func (w *ServerInterfaceWrapper) SubscribeEventWS(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params SubscribeEventWSParams
	// ------------- Optional query parameter "names" -------------

	err = runtime.BindQueryParameter("form", true, false, "names", ctx.QueryParams(), &params.Names)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter names: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SubscribeEventWS(ctx, sourceId, params)
	return err
}

// PublishEvent converts echo context to params.
func (w *ServerInterfaceWrapper) PublishEvent(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name EventName

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PublishEvent(ctx, sourceId, name)
	return err
}

// GetEventTypes converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventTypes(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetEventTypes(ctx)
	return err
}

// RegisterEventTypes converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterEventTypes(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RegisterEventTypes(ctx)
	return err
}

// GetEventTypesBySourceID converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventTypesBySourceID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetEventTypesBySourceID(ctx, sourceId)
	return err
}

// GetEventType converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventType(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name EventName

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetEventType(ctx, sourceId, name)
	return err
}

// SubscribeSIO converts echo context to params.
func (w *ServerInterfaceWrapper) SubscribeSIO(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SubscribeSIO(ctx)
	return err
}

// PollSIO converts echo context to params.
func (w *ServerInterfaceWrapper) PollSIO(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PollSIO(ctx)
	return err
}

// SubscribeSIO2 converts echo context to params.
func (w *ServerInterfaceWrapper) SubscribeSIO2(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SubscribeSIO2(ctx)
	return err
}

// PollSIO2 converts echo context to params.
func (w *ServerInterfaceWrapper) PollSIO2(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PollSIO2(ctx)
	return err
}

// IssueSubscriptionTicket converts echo context to params.
func (w *ServerInterfaceWrapper) IssueSubscriptionTicket(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.IssueSubscriptionTicket(ctx)
	return err
}

// GetYskCard converts echo context to params.
func (w *ServerInterfaceWrapper) GetYskCard(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetYskCard(ctx)
	return err
}

// DeleteYskCard converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteYskCard(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteYskCard(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/action/:source_id", wrapper.SubscribeActionWS)
	router.POST(baseURL+"/action/:source_id/:name", wrapper.TriggerAction)
	router.GET(baseURL+"/action_type", wrapper.GetActionTypes)
	router.POST(baseURL+"/action_type", wrapper.RegisterActionTypes)
	router.GET(baseURL+"/action_type/:source_id", wrapper.GetActionTypesBySourceID)
	router.GET(baseURL+"/action_type/:source_id/:name", wrapper.GetActionType)
	router.GET(baseURL+"/event/:source_id", wrapper.SubscribeEventWS)
	router.POST(baseURL+"/event/:source_id/:name", wrapper.PublishEvent)
	router.GET(baseURL+"/event_type", wrapper.GetEventTypes)
	router.POST(baseURL+"/event_type", wrapper.RegisterEventTypes)
	router.GET(baseURL+"/event_type/:source_id", wrapper.GetEventTypesBySourceID)
	router.GET(baseURL+"/event_type/:source_id/:name", wrapper.GetEventType)
	router.GET(baseURL+"/socket.io", wrapper.SubscribeSIO)
	router.POST(baseURL+"/socket.io", wrapper.PollSIO)
	router.GET(baseURL+"/socket.io/", wrapper.SubscribeSIO2)
	router.POST(baseURL+"/socket.io/", wrapper.PollSIO2)
	router.POST(baseURL+"/ticket", wrapper.IssueSubscriptionTicket)
	router.GET(baseURL+"/ysk", wrapper.GetYskCard)
	router.DELETE(baseURL+"/ysk/:id", wrapper.DeleteYskCard)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcbW/bOLb+Kwe6F9gWkO20zezOGJgPTTLTCbozKers7R00QUxJxzbHEqkhKSeeIv99",
	"QVIv1Itt2XFTYLGfWtvieXnOw8NzSCpfvJAnKWfIlPTGX7yUCJKgQmE+vQ0V5ew3kqD+RJk39lKiFp7v",
	"MfOd/cf3BP6ZUYGRN1YiQ9+T4QITosfgA0nSWD8a85DEA6m4IHMcp0QoqoWPZ1wkRHm+p9apfk4qQdnc",
	"e3z0HfVyH1n+pp8TnjGtyTjyZ4ZiXfdEeq7pVGFi9DYMKy0lQpC1MfSnFTL1NWCKqFyOSRRh1AlQqVf2",
	"E+J3/CAw4Ssj/+iwTHgmQry82ICKND/f0egQaDrweLRiUKozHlGLyYcsiKlcGKD055Azlf+XpGlMQ6KZ",
	"MfpDcqa/q9SSKDKkIfEHwVMUKhfY8jpCGQqa6me9sYdaEaTVEL9y4EsjLgmPMPbG3rnI/kLh+Y2fs4xG",
	"3tg7PX2NJ/hdMPgheoOD0xl+PwhO/z4b/BCevjp9NYswjP7RGrtCFnHhjb0JYRdULp3w8OAPDJWFq277",
	"i+uri6uXrWA8+t5HnFOpUNgJeb1OLRa9wSw5878CZ97Y+59RlXVG9jE5qoR3kOkAY03Mv5KtpeynmXot",
	"6HxewPoc9CRGU09+7kPAp/DLzFuZciatD+9QVVy4er8XLn0J1rbu6r12oqZb7qn8K9C8tKpk3BEBcVjc",
	"R/NXgWOvmWRtcnP6sdHYrPVjTtEzEn20q0wPzc7cSlBKvW6NvTMSQSHi0e9p3RmRWJjQZWRDaPHoOWez",
	"mIYH21qOP5qhrsTiuZ+5CGgUITvUzErA0eysiSwefIfq98n7cyKif1K5L/lIHF/NvPHnfezyv3hpLcFH",
	"RO10zTFRe3a7k9OXTKFgJJ6gWKH4SQhdOxxpWu3COV8VHGt+4+pnnrHoUDL8xhVYAUcjQ01k8eARc88u",
	"/fVwXXP+K2HrfLrLQ3G65hy0HCgFHQ2vTtG1aufo6/om2EqfnI7WdLq1acXy5q2zXMrbt6391aY21m8o",
	"+o/vK/y8r7NtXwNPKXlIicII7ENgmr/eLZ7vKZqgVCRJ28LLn0AtqIQ8dorzJaQxCbW4PEhjnUVxoAd0",
	"ttVVffq5csYvungnCLcd3jv13f4su2E37IVaoECgEhjXX1I2h5AzTQD92IwLcEZIH4JMAVV6gMCQJwmy",
	"CCNQZjACknABRIJUIgtVJkgMhEVQmrBC/WvKpaRBjC+fzPO1dt0sPX1LwA/OwHYVuJVPFoeSS9ppGmmg",
	"Zmu4NzCqBRZw3dM4BkWWuA/l+tKhcruLFLV82aJFmZKb/uU/gECVCYYRBGuQZo0GSSMEOoOSLISta36Z",
	"PotEVyxeF5sqHRsm5cZIH6LaJNQnG27YsvpvMvxGydAitncu9D2LTzcRzG+uwT1RPHLCrTrIvWncM91W",
	"A5472+6aR8+ZbC0Ku3KtfSrkCUqYCZ48f66tediiRM0nd3f5FyKieyIQ7LQGPrNTZ8v8c5JOJadIBh3P",
	"d9OxcKpk5E12cvIG4bJFMrP0Q+15HYXAcGoDxYZwxRC4UablKQ6pwBl9gHuqFkAsrVMS4rDUPIBLs7BU",
	"qjQONvAyxZDOaOjXxOQ/Xl4M4Wc9YSwaPky7MubUUXSlZ989lViXN9VOczaeNuXl32NCaFzKKeVNeIIQ",
	"kKgYIEEHdEqjqQ9TstJjfJgG8XI6HA7vFzRcQEiYATAJ6DzjmTTTNeRslknK5sMtEzRP/7tYbILexdO8",
	"S29TNCQiKsiLLEu0FEUMpWLO5gPGFTUpXC64UMXH2w7COe1Vj/2C8/zpR9+zSb/y/NXrN6ff/f0f3/9w",
	"0sVroekpNplMpapMpiFnA4UPzlcJEcuI37PNjjQQNatOCVJNfeXyFsTPK1TqwAc8Wl+GnH2ianGND31x",
	"qw159I2YvXKys19zqTDpSsta5gfB5wJlX3Hl4496sefl8Y3c166fncFdtimqYtQg7IFXOa7AueLaOZHk",
	"arJzXlVaXUlbwl5zY1MNfpb1ReXXckCFjC7K6878H8V7uEBFaCy7po5U6+YCsqJ4P4g2D1EtxBZKpXI8",
	"GoVEEi6HoVl1d6yt2tJCfS7Td0HYAmQR6rYBgtwP51QtsiCTKPKpqO0ZXYb4aUF0kMLFKOZzPkoIZbnF",
	"+T93AWEMxZ26pzGdL9RdEGd49/3JSfowTNm8C4uuGdh/yd/ENJum9mJzM0VZXrqatwB6SLLomojNPPJN",
	"kPA9oYPXntencH22k5cdwLkCt4DYmo8t75e4rlvEU2SDTMSdBTZZx5xET55oWmklbYv9bnav2x2TQLew",
	"riGXTCoSx7pX+QPjeD2jbEOXUMosB393Uj5JmcI5ipbRVqMzvm23zl0YZoKq9UTTIG/owxClvFN8ac9y",
	"zK2PBZLItN75vY+3mVpwQf8ieXgLGqf0PebHfpTNeLtSNlVemFLdWGFR+gEA2B/yIjTBiJIfb7wXuqBE",
	"IQchj7kYGLLiGCIili9vPJAilKh+vDly8tLi75hJX2XmuvEONdbkwa9o7YZU22UwTeZAYm2CTRbWqOe3",
	"yFozarDghlmrIE8DcKZL+TDEVOW7H7ayt1uBtjWFFRFUl/w2FjLv1GO6QiF1/5PobklmgeZggELqDonp",
	"foRKmRXPUxlmUmqhPqQxEomwopIq00B9fkfVL1kAAlMuqeJiffuiwMti1QbIOvISuIA/OGXwmWcCLqgM",
	"uYiq0ZH9Yjifj5bsz7dBcBbg/78c3pTlUJnVa5C8/XDp+Z520E6p1WudJ3QiJCn1xt6b4cnwjUlYamFm",
	"9MgiNvpS3tZ61F/PUbXn56SASuNWIB2sYVqOncKKEviEwYSHS1RDp92dmkZ0WjRkeZ+JEVBmoDQX08Dm",
	"tlpczIe8Ky13/dcpSguGzqQm01xGrol2kfg0Mb5Wdx43HM5Wj4zKS22P/s5n3QuMj7eNay6vTl61Ibxe",
	"oO4+GTpb1gFCls4FyfeZHPzcRzUZNU5hTJEpO1JgiGY/II8FMbRem65Y2dM4jDRMJp1nSULEekscyy4f",
	"XpQmvNR8I3MNnVfZ9ROLUk6Zkt6tFt1BotEXHW/DpZTLDjLlp4VAWBFUbolQbIoHWWeE63eqnie6eXCL",
	"u4frTQVT7XriqG5p8xbU65OTzWLy50bNI9VH3zvtM67jMosZetp/aHlKX+dOK2wOP6yZkKBa8KhOjTuV",
	"7x50JhZd0QKJ49r0BrUgylA5zIRApuI1iPzuH0Z2H6kHX+o3vrxDotC6NFaHxFrvWN6CRI9zYPE3TIni",
	"ZiNwhnp5SLhAYHhfh6Wv412XOg9gcZeYg7jsXKt4Ko1/6D+0uo5Ui1kn1PvEsEHtXuvnO9zG8h3czneH",
	"y5Ww2pLdSfqz9aTaaj80X94eZ+YcJwsZJF0U3dXrCaFzVq3NEWSuahs/s5F/WPicstXs1e8M5/OueU+K",
	"+JEDXge+VrBoEPNDpJ2xN+3C/gWvPfl63nI3P9fdWe2aM9KvXOw6L6N8y1q3aPacUje1F4Z3lrr50CdV",
	"ui3y7Cx08+vMmr7FMX2f5bv2ZsuzxPWwKrdm50GFQeO+97evcZsRc4hhjOzKJz0LXGdCH6++dd6EOTBl",
	"194BePS97/YJQNft4o4K2XG9CehT62MX1X3L4wZ4B1bHjpT/0OK4f/jqc2Kvyrhzehy5MK5C9U3r4uaU",
	"O1aV5EK4oSreL2g9a+JK73FK4upS1q44Puvq+JRIH70cdjDfVQ1virm0lSvlexTB9a12XQLbYunyylTA",
	"g/IjTAXnyRTkgmdxpIs/pGqBAqZGzlQnl6mVM91W3k4ur7yjVZylcccqOP2CCY26j9sDPMqooiSmf+U3",
	"vAr9vWpVF+gXxUi3Ui29cQvVTQuoNqlLcrBuRrFdjvI47gjDVs9DzhRlmfZb8GSz45vM6u9wjcmjjVQu",
	"rpGRxNyhm1ZjpoAPIabm6qe93Jhfn1OCUOOMjIlcwHQ0hQEQuOdiSYSemTpYCXmgCf1Lky9JiaIBjala",
	"72D06/9S2o3wRtJ+86Dl1H/9rbhv2K2o/ri5yzwT/F6ikBASxrgCaVeIae0wfgr2rB40P6rW27dk4Utk",
	"9kYlwxWK/HgVoxtGGfzr4z8lvDB0iZEsgTLFIeZz6cOCSsXF2ggxp9wo5MshvIXA2mTfYZiZHVa5LJZ9",
	"69ANm1EhlW8jR5UExkVC4g2G+wWtGfBUW6sZnm+dGCTMAqTnjBVvq5D85QrO4rVmEIGQ8yXFMQjCIp74",
	"sCIxtUzWFa8rDxaERXJBlqg13zCiIOFSwZsTkBhyFkkfgoJR2phMmsORCP4lUQzezpEpH6a/KJVesXg9",
	"9WGqiTyhCn+cKEFDNfWtZBnyFHMx1Bzk/k1CStTCB2lFF3BKZJHUnC+Lqmq7omYuMG4ubt8wjCUOQeMi",
	"9TRKidItW54AQHBDGLGiIf5NwmTyCygUCWUk1iGmrGtBuJQyw4kD1bVlaGuSnHYktSI4Mqt2xKYTVINz",
	"E5ki3ENbL73pXy/V3uo9fb1HL9R86bI+TY23ulh1uaEKj7esTb73CQPZvZe0lsutVTVDNBcQ0pis4ffJ",
	"ewiJiLpK4d/l8tz+dHjn2Xr1+VjbAAU42oEOBEZf8sYwwhhVx/3537jaDcKFGVzh0GgI6hILKfaFnI6/",
	"XLPjT9Y0b4TdPr3j/7pIO5e5DBz1a1yfb7UH9r0zC1cmYm/sjVavR3m7dhdkdtc3V9F+kc30FCaFJoSR",
	"uV4CnU7U16nmHuPYvLpgSw39iE5Sxc53vhFu18IqFvUdN92x9VDtng3toTtffJ2rbPUT7bb2AmaTqa0R",
	"nf60OqYyZVfKuhLFETUWyalS2JGueukr548W+/GnyfUsi/ObR7nkOgPbQu0lL3OxkFzgzNSTnIGdYh9x",
	"9uPNjr8mcuPByBaGDabk7z0dVeFGZUdUVJ1WdWmr/VGZ46rcrO6Iqtx3troUNt5a6zXHnbXAYV05VW99",
	"72GgyPyd4Flqc1b+2K/5I9s2R/xG3vG7jhP9Zn7waybcakcKujgFwbZDJr+7hmhm9ErwJP/bBx3OFE7U",
	"jC8/eI036W4fbx//HQAA//9T4IVjLlAAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
