// Package codegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version (devel) DO NOT EDIT.
package codegen

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

const (
	Access_tokenScopes = "access_token.Scopes"
)

// Defines values for YSKCardCardType.
const (
	YSKCardCardTypeLongNotice  YSKCardCardType = "long-notice"
	YSKCardCardTypeShortNotice YSKCardCardType = "short-notice"
	YSKCardCardTypeTask        YSKCardCardType = "task"
)

// Defines values for YSKCardRenderType.
const (
	YSKCardRenderTypeIconTextNotice YSKCardRenderType = "icon-text-notice"
	YSKCardRenderTypeListNotice     YSKCardRenderType = "list-notice"
	YSKCardRenderTypeMarkdownNotice YSKCardRenderType = "markdown-notice"
	YSKCardRenderTypeTask           YSKCardRenderType = "task"
)

// Action defines model for Action.
type Action struct {
	// Name action name
	Name string `json:"name"`

	// Properties event properties
	Properties map[string]string `json:"properties"`

	// SourceID associated source id
	SourceID string `json:"sourceID"`

	// Timestamp timestamp this action took place
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// ActionType defines model for ActionType.
type ActionType struct {
	// Name action name
	//
	// (there is no naming convention for action names, but it is recommended to name each as structural and descriptive as possible)
	Name             string         `json:"name"`
	PropertyTypeList []PropertyType `json:"propertyTypeList"`

	// SourceID action source id to identify where the action will take
	SourceID string `json:"sourceID"`
}

// BaseResponse defines model for BaseResponse.
type BaseResponse struct {
	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// Event defines model for Event.
type Event struct {
	// Name event name
	Name string `json:"name"`

	// Properties event properties
	Properties map[string]string `json:"properties"`

	// SourceID associated source id
	SourceID string `json:"sourceID"`

	// Timestamp timestamp this event took place
	Timestamp *time.Time `json:"timestamp,omitempty"`

	// Uuid event uuid
	Uuid *string `json:"uuid,omitempty"`
}

// EventType defines model for EventType.
type EventType struct {
	// Name event name
	//
	// (there is no naming convention for event names, but it is recommended to name each as structural and descriptive as possible)
	Name             string         `json:"name"`
	PropertyTypeList []PropertyType `json:"propertyTypeList"`

	// SourceID event source id to identify where the event comes from
	SourceID string `json:"sourceID"`
}

// PropertyType defines model for PropertyType.
type PropertyType struct {
	Description *string `json:"description,omitempty"`
	Example     *string `json:"example,omitempty"`

	// Name property name
	//
	// > It is recommended for a property name to be as descriptive as possible. One option is to prefix with a namespace.
	// > - If the property is source specific, prefix with source ID. For example, `local-storage:vendor`
	// > - Otherwise, prefix with `common:`. For example, `common:email`
	// >
	// > Some bad examples are `id`, `avail`, `blk`...which can be ambiguous and confusing.
	Name string `json:"name"`
}

// YSKCard defines model for YSKCard.
type YSKCard struct {
	CardType   YSKCardCardType   `json:"cardType"`
	Content    YSKCardContent    `json:"content"`
	Id         string            `json:"id"`
	RenderType YSKCardRenderType `json:"renderType"`
}

// YSKCardCardType defines model for YSKCard.CardType.
type YSKCardCardType string

// YSKCardRenderType defines model for YSKCard.RenderType.
type YSKCardRenderType string

// YSKCardContent defines model for YSKCardContent.
type YSKCardContent struct {
	BodyIconWithText *YSKCardIconWithText   `json:"bodyIconWithText,omitempty"`
	BodyList         *[]YSKCardListItem     `json:"bodyList,omitempty"`
	BodyProgress     *YSKCardProgress       `json:"bodyProgress,omitempty"`
	FooterActions    *[]YSKCardFooterAction `json:"footerActions,omitempty"`
	TitleIcon        YSKCardIcon            `json:"titleIcon"`
	TitleText        string                 `json:"titleText"`
}

// YSKCardFooterAction defines model for YSKCardFooterAction.
type YSKCardFooterAction struct {
	MessageBus YSKCardMessageBusAction `json:"messageBus"`
	Side       string                  `json:"side"`
	Style      string                  `json:"style"`
	Text       string                  `json:"text"`
}

// YSKCardIcon defines model for YSKCardIcon.
type YSKCardIcon = string

// YSKCardIconWithText defines model for YSKCardIconWithText.
type YSKCardIconWithText struct {
	Description string      `json:"description"`
	Icon        YSKCardIcon `json:"icon"`
}

// YSKCardList defines model for YSKCardList.
type YSKCardList = []YSKCard

// YSKCardListItem defines model for YSKCardListItem.
type YSKCardListItem struct {
	Description string      `json:"description"`
	Icon        YSKCardIcon `json:"icon"`
	RightText   string      `json:"rightText"`
}

// YSKCardMessageBusAction defines model for YSKCardMessageBusAction.
type YSKCardMessageBusAction struct {
	Key     string `json:"key"`
	Payload string `json:"payload"`
}

// YSKCardProgress defines model for YSKCardProgress.
type YSKCardProgress struct {
	Label    string `json:"label"`
	Progress int    `json:"progress"`
}

// ActionName defines model for ActionName.
type ActionName = string

// ActionNames defines model for ActionNames.
type ActionNames = []string

// EventName defines model for EventName.
type EventName = string

// EventNames defines model for EventNames.
type EventNames = []string

// SourceID defines model for SourceID.
type SourceID = string

// GetActionTypeOK defines model for GetActionTypeOK.
type GetActionTypeOK = ActionType

// GetActionTypesOK defines model for GetActionTypesOK.
type GetActionTypesOK = []ActionType

// GetEventTypeOK defines model for GetEventTypeOK.
type GetEventTypeOK = EventType

// GetEventTypesOK defines model for GetEventTypesOK.
type GetEventTypesOK = []EventType

// PublishEventOK defines model for PublishEventOK.
type PublishEventOK = Event

// ResponseBadRequest defines model for ResponseBadRequest.
type ResponseBadRequest = BaseResponse

// ResponseConflict defines model for ResponseConflict.
type ResponseConflict = BaseResponse

// ResponseForbidden defines model for ResponseForbidden.
type ResponseForbidden = BaseResponse

// ResponseGetYSKCardListOK defines model for ResponseGetYSKCardListOK.
type ResponseGetYSKCardListOK struct {
	Data *YSKCardList `json:"data,omitempty"`

	// Message message returned by server side if there is any
	Message *string `json:"message,omitempty"`
}

// ResponseInternalServerError defines model for ResponseInternalServerError.
type ResponseInternalServerError = BaseResponse

// ResponseNotFound defines model for ResponseNotFound.
type ResponseNotFound = BaseResponse

// ResponseOK defines model for ResponseOK.
type ResponseOK = BaseResponse

// ResponseTooManyRequests defines model for ResponseTooManyRequests.
type ResponseTooManyRequests = BaseResponse

// TriggerActionOK defines model for TriggerActionOK.
type TriggerActionOK = Action

// PublishEvent event properties
type PublishEvent map[string]string

// RegisterActionTypes defines model for RegisterActionTypes.
type RegisterActionTypes = []ActionType

// RegisterEventTypes defines model for RegisterEventTypes.
type RegisterEventTypes = []EventType

// TriggerAction action properties
type TriggerAction map[string]string

// SubscribeActionWSParams defines parameters for SubscribeActionWS.
type SubscribeActionWSParams struct {
	Names *ActionNames `form:"names,omitempty" json:"names,omitempty"`
}

// TriggerActionJSONBody defines parameters for TriggerAction.
type TriggerActionJSONBody map[string]string

// RegisterActionTypesJSONBody defines parameters for RegisterActionTypes.
type RegisterActionTypesJSONBody = []ActionType

// SubscribeEventWSParams defines parameters for SubscribeEventWS.
type SubscribeEventWSParams struct {
	Names *EventNames `form:"names,omitempty" json:"names,omitempty"`
}

// PublishEventJSONBody defines parameters for PublishEvent.
type PublishEventJSONBody map[string]string

// RegisterEventTypesJSONBody defines parameters for RegisterEventTypes.
type RegisterEventTypesJSONBody = []EventType

// TriggerActionJSONRequestBody defines body for TriggerAction for application/json ContentType.
type TriggerActionJSONRequestBody TriggerActionJSONBody

// RegisterActionTypesJSONRequestBody defines body for RegisterActionTypes for application/json ContentType.
type RegisterActionTypesJSONRequestBody = RegisterActionTypesJSONBody

// PublishEventJSONRequestBody defines body for PublishEvent for application/json ContentType.
type PublishEventJSONRequestBody PublishEventJSONBody

// RegisterEventTypesJSONRequestBody defines body for RegisterEventTypes for application/json ContentType.
type RegisterEventTypesJSONRequestBody = RegisterEventTypesJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Subscribe to actions by source ID (WebSocket)
	// (GET /action/{source_id})
	SubscribeActionWS(ctx echo.Context, sourceId SourceID, params SubscribeActionWSParams) error
	// Trigger an action
	// (POST /action/{source_id}/{name})
	TriggerAction(ctx echo.Context, sourceId SourceID, name ActionName) error
	// List action types
	// (GET /action_type)
	GetActionTypes(ctx echo.Context) error
	// Register one or more action types
	// (POST /action_type)
	RegisterActionTypes(ctx echo.Context) error
	// Get action types by source ID
	// (GET /action_type/{source_id})
	GetActionTypesBySourceID(ctx echo.Context, sourceId SourceID) error
	// Get an action type by source ID and name
	// (GET /action_type/{source_id}/{name})
	GetActionType(ctx echo.Context, sourceId SourceID, name ActionName) error
	// Subscribe to events by source ID (WebSocket)
	// (GET /event/{source_id})
	SubscribeEventWS(ctx echo.Context, sourceId SourceID, params SubscribeEventWSParams) error
	// Publish an event
	// (POST /event/{source_id}/{name})
	PublishEvent(ctx echo.Context, sourceId SourceID, name EventName) error
	// List event types
	// (GET /event_type)
	GetEventTypes(ctx echo.Context) error
	// Register one or more event types
	// (POST /event_type)
	RegisterEventTypes(ctx echo.Context) error
	// Get event types by source ID
	// (GET /event_type/{source_id})
	GetEventTypesBySourceID(ctx echo.Context, sourceId SourceID) error
	// Get an event type by source ID and name
	// (GET /event_type/{source_id}/{name})
	GetEventType(ctx echo.Context, sourceId SourceID, name EventName) error
	// Subscribe to events and actions (SocketIO)
	// (GET /socket.io)
	SubscribeSIO(ctx echo.Context) error
	// Poll events and actions (SocketIO)
	// (POST /socket.io)
	PollSIO(ctx echo.Context) error
	// Subscribe to events and actions (SocketIO)
	// (GET /socket.io/)
	SubscribeSIO2(ctx echo.Context) error
	// Poll events and actions (SocketIO)
	// (POST /socket.io/)
	PollSIO2(ctx echo.Context) error
	// Issue a subscription ticket
	// (POST /ticket)
	IssueSubscriptionTicket(ctx echo.Context) error

	// (GET /ysk)
	GetYskCard(ctx echo.Context) error

	// (DELETE /ysk/{id})
	DeleteYskCard(ctx echo.Context, id string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// SubscribeActionWS converts echo context to params.
func (w *ServerInterfaceWrapper) SubscribeActionWS(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params SubscribeActionWSParams
	// ------------- Optional query parameter "names" -------------

	err = runtime.BindQueryParameter("form", true, false, "names", ctx.QueryParams(), &params.Names)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter names: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SubscribeActionWS(ctx, sourceId, params)
	return err
}

// TriggerAction converts echo context to params.
func (w *ServerInterfaceWrapper) TriggerAction(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name ActionName

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.TriggerAction(ctx, sourceId, name)
	return err
}

// GetActionTypes converts echo context to params.
func (w *ServerInterfaceWrapper) GetActionTypes(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetActionTypes(ctx)
	return err
}

// RegisterActionTypes converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterActionTypes(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RegisterActionTypes(ctx)
	return err
}

// GetActionTypesBySourceID converts echo context to params.
func (w *ServerInterfaceWrapper) GetActionTypesBySourceID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetActionTypesBySourceID(ctx, sourceId)
	return err
}

// GetActionType converts echo context to params.
func (w *ServerInterfaceWrapper) GetActionType(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name ActionName

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetActionType(ctx, sourceId, name)
	return err
}

// SubscribeEventWS converts echo context to params.
func (w *ServerInterfaceWrapper) SubscribeEventWS(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params SubscribeEventWSParams
	// ------------- Optional query parameter "names" -------------

	err = runtime.BindQueryParameter("form", true, false, "names", ctx.QueryParams(), &params.Names)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter names: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SubscribeEventWS(ctx, sourceId, params)
	return err
}

// PublishEvent converts echo context to params.
func (w *ServerInterfaceWrapper) PublishEvent(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name EventName

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PublishEvent(ctx, sourceId, name)
	return err
}

// GetEventTypes converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventTypes(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetEventTypes(ctx)
	return err
}

// RegisterEventTypes converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterEventTypes(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.RegisterEventTypes(ctx)
	return err
}

// GetEventTypesBySourceID converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventTypesBySourceID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetEventTypesBySourceID(ctx, sourceId)
	return err
}

// GetEventType converts echo context to params.
func (w *ServerInterfaceWrapper) GetEventType(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "source_id" -------------
	var sourceId SourceID

	err = runtime.BindStyledParameterWithLocation("simple", false, "source_id", runtime.ParamLocationPath, ctx.Param("source_id"), &sourceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter source_id: %s", err))
	}

	// ------------- Path parameter "name" -------------
	var name EventName

	err = runtime.BindStyledParameterWithLocation("simple", false, "name", runtime.ParamLocationPath, ctx.Param("name"), &name)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetEventType(ctx, sourceId, name)
	return err
}

// SubscribeSIO converts echo context to params.
func (w *ServerInterfaceWrapper) SubscribeSIO(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SubscribeSIO(ctx)
	return err
}

// PollSIO converts echo context to params.
func (w *ServerInterfaceWrapper) PollSIO(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PollSIO(ctx)
	return err
}

// SubscribeSIO2 converts echo context to params.
func (w *ServerInterfaceWrapper) SubscribeSIO2(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.SubscribeSIO2(ctx)
	return err
}

// PollSIO2 converts echo context to params.
func (w *ServerInterfaceWrapper) PollSIO2(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PollSIO2(ctx)
	return err
}

// IssueSubscriptionTicket converts echo context to params.
func (w *ServerInterfaceWrapper) IssueSubscriptionTicket(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.IssueSubscriptionTicket(ctx)
	return err
}

// GetYskCard converts echo context to params.
func (w *ServerInterfaceWrapper) GetYskCard(ctx echo.Context) error {
	var err error

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetYskCard(ctx)
	return err
}

// DeleteYskCard converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteYskCard(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	ctx.Set(Access_tokenScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeleteYskCard(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/action/:source_id", wrapper.SubscribeActionWS)
	router.POST(baseURL+"/action/:source_id/:name", wrapper.TriggerAction)
	router.GET(baseURL+"/action_type", wrapper.GetActionTypes)
	router.POST(baseURL+"/action_type", wrapper.RegisterActionTypes)
	router.GET(baseURL+"/action_type/:source_id", wrapper.GetActionTypesBySourceID)
	router.GET(baseURL+"/action_type/:source_id/:name", wrapper.GetActionType)
	router.GET(baseURL+"/event/:source_id", wrapper.SubscribeEventWS)
	router.POST(baseURL+"/event/:source_id/:name", wrapper.PublishEvent)
	router.GET(baseURL+"/event_type", wrapper.GetEventTypes)
	router.POST(baseURL+"/event_type", wrapper.RegisterEventTypes)
	router.GET(baseURL+"/event_type/:source_id", wrapper.GetEventTypesBySourceID)
	router.GET(baseURL+"/event_type/:source_id/:name", wrapper.GetEventType)
	router.GET(baseURL+"/socket.io", wrapper.SubscribeSIO)
	router.POST(baseURL+"/socket.io", wrapper.PollSIO)
	router.GET(baseURL+"/socket.io/", wrapper.SubscribeSIO2)
	router.POST(baseURL+"/socket.io/", wrapper.PollSIO2)
	router.POST(baseURL+"/ticket", wrapper.IssueSubscriptionTicket)
	router.GET(baseURL+"/ysk", wrapper.GetYskCard)
	router.DELETE(baseURL+"/ysk/:id", wrapper.DeleteYskCard)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xc/W7bOpZ/FUK7wLRY2U7T3JlbD/pHk/Qj6NymqDPbvWiCmJKObdYSqUtSSdQiD7Dv",
	"sU+2TzLghyTqw7bsuCkwuH+1tsXz8Ts/Hp5DUvnuhSxJGQUqhTf+7qWY4wQkcP3pVSgJox9wAuoTod7Y",
	"S7FceL5H9XfmH9/j8EdGOETeWPIMfE+EC0iwGgN3OElj9WjMQhwPhGQcz2GcYi6JEj6eMZ5g6fmezFP1",
	"nJCc0Ll3f+876sU2svxVPycso0qTduSPDHhe90R4rulEQqL1NgwrLcWc41wb+voGqPwRMEVELMc4iiDq",
	"BKjUK/oJ8Tt+4JCwGy1/77BMWMZDODtdgYrQP1+TaBdoOvC4N2JAyGMWEYPJxyyIiVhooNTnkFFp/4vT",
	"NCYhVswYfRWMqu8qtTiKNGlw/JGzFLi0AlteRyBCTlL1rDf2QClCaTXErxz43ohLwiKIvbF3wrNvwD2/",
	"8XOWkcgbe0dHh3AAvwSDF9FzGBzN4NdBcPTX2eBFePTs6NksgjD6W2vsDdCIcW/sTTA9JWLphIcFXyGU",
	"Bq667U8uzk/Pn7aCce97n2BOhARuJuRFnhoseoNZcuY/Ocy8sfcfoyrrjMxjYlQJ7yDTDsbqmP8gW0vZ",
	"DzP1gpP5vID1MeiJtaae/NyGgA/hl563ImVUGB/egqy4cP5+K1z6Eqxt3fl75URNt9hS+Q+geWlVybg9",
	"AuKwuI/mHwLHVjPJ2OTm9H2jsVrrJ0vRYxx9MqtMD83O3EpACLVujb1jHKFCxL3f07pjLKAwocvIhtDi",
	"0RNGZzEJd7a1HL83Q12JxXNvGA9IFAHd1cxKwN7srIksHnwL8vfJ+xPMo38QsS35cByfz7zxl23s8r97",
	"aS3BR1hudM0xUXl2tZHTZ1QCpzieAL8B/ppzVTvsaVptwtmuCo41H5h8wzIa7UqGD0wiI2BvZKiJLB7c",
	"Y+7ZpL8ergvGfsM0t9Nd7IrTBWNIyUGloL3h1Sm6Vu3sfV1fBVvpk9PR6k63Nq2obd46yyXbvq3tr1a1",
	"sX5D0b99X+Hbvs60fQ08hWAhwRIiZB5Cuvnr3eL5niQJCImTtC28/AnJBRHIxk4ytkRpjEMlzgZprLIo",
	"DNSAzra6qk+/VM74RRfvBOGqw3unvtueZZf0kj6RC+CAiECUqS8JnaOQUUUA9diMceSMED4KMomIVAM4",
	"hCxJgEYQIakHAwIcLhAWSEiehTLjOEaYRqg04QbUrykTggQxPH0wz3Plul56+paAH52B7SpwLZ8MDiWX",
	"lNMkUkDNcnSrYZQLKOC6JXGMJF7CNpTrS4fK7S5S1PJlixZlSm76Z39AHGTGKUQoyJHQazQSJAJEZqgk",
	"C6Z5zS/dZ+HonMZ5sanSsWFSboz0IapJQn2y4Yotqz+T4U9KhgaxrXOh7xl8uomgf3MN7oninhNu1UFu",
	"TeOe6bYa8NjZdtM8esxka1DYlGvNUyFLQKAZZ8nj59qahy1K1Hxyd5ffYR7dYg7ITGvEZmbqrJl/TtKp",
	"5BTJoOP5bjoWTpWMvMwODp4DOmuRTC/9qPa8ikKgObWCYkN0TgExrUzJkwylHGbkDt0SuUDY0DrFIQxL",
	"zQN0pheWSpXCwQRepBCSGQn9mhj749npEL1RE8ag4aNpV8acOorO1ey7JQLq8qbKaUbH06Y8+z0kmMSl",
	"nFLehCWAAhwVAwRSAZ2SaOqjKb5RY3w0DeLldDgc3i5IuEAhphrAJCDzjGVCT9eQ0VkmCJ0P10xQm/43",
	"sVgHvYuntktvUzTEPCrICzRLlBSJNaViRucDyiTRKVwsGJfFx6sOwjntVY/9ghP79L3vmaRfef7s8PnR",
	"L3/9268vDrp4zRU9+SqTiZCVySRkdCDhzvkqwXwZsVu62pEGonrVKUGqqa9cXoP4SYVKHfiARflZyOhn",
	"IhcXcNcXt9qQe1+L2SonO/s1ZxKSrrSsZH7kbM5B9BVXPn6vFntWHt+Ibe164wzusk0SGYMCYQu8ynEF",
	"zhXXTrDA55ON86rS6kpaE/aaG6tq8OOsLyq/lQMqZFRRXnfmvwncolOQmMSia+oImTcXkBsCt4No9RDZ",
	"QmwhZSrGo1GIBWZiGOpVd8Paqiwt1FuZvgvCGiCLULcN4Ph2OCdykQWZAG6norJndBbC5wVWQQoXo5jN",
	"2SjBhFqL7T/XAaYU+LW8JTGZL+R1EGdw/evBQXo3TOm8C4uuGdh/yV/FNJOmtmJzM0UZXrqa1wC6S7Lo",
	"mojNPPJTkPA9roLXntdH6OJ4Iy87gHMFrgGxNR9b3i8hr1vEUqCDjMedBTbOY4ajB080pbSStsZ+N7vX",
	"7Y5xoFpY15AzKiSOY9WrfIU4zmeErugSSpnl4F8OyicJlTAH3jLaaHTGt+1WuQvCjBOZTxQNbEMfhiDE",
	"tWRLc5ajb30sAEe69bb3Pl5lcsE4+YZteAsap+Q92GM/QmesXSnrKi9MiWqsoCj9EELI/GCL0AQigl9e",
	"ek9UQQlcDEIWMz7QZIUxijBfPr30kOChAPnycs/JS4m/pjp9lZnr0tvVWJ0Hf6C1K1Jtl8EkmSMcKxNM",
	"sjBGPb5FxppRgwWX1FiFbBpAx6qUD0NIpd39MJW92Qo0rSm6wZyokt/EQthOPSY3wIXqfxLVLYksUBwM",
	"gAvVIVHVjxAhsuJ5IsJMCCXUR2kMWAC6IYJI3UB9eUvkuyxAHFImiGQ8v3pS4GWwagNkHHmKGEdfGaHo",
	"C8s4OiUiZDyqRkfmi+F8PlrSP14FwXEA//N0eFmWQ2VWr0Hy6uOZ53vKQTOlbg5VnlCJEKfEG3vPhwfD",
	"5zphyYWe0SOD2Oh7eVvrXn09B9men5MCKoVbgXSQo2k5dopuCEafIZiwcAly6LS7U92ITouGzPaZECFC",
	"NZT6Yhoyua0WF/3BdqXlrn+egjBgqEyqM81Z5JpoFonPE+1rdedxxeFs9ciovNR272981r3AeH/VuOby",
	"7OBZG8KLBajuk4KzZR0AytI5x3afycHPfVSRUeEUxgSoNCM5hKD3A2wssKZ1rrtiaU7jIFIw6XSeJQnm",
	"+Zo4ll0+elKa8FTxDc8VdF5l12sapYxQKbwrJbqDRKPvKt6aSykTHWSyp4UI0yKozBCh2BQPss4I1+9U",
	"PU50bXCLu4f5qoKpdj1xVLe0eQvq8OBgtRj73Kh5pHrve0d9xnVcZtFDj/oPLU/p69xphc3hhzETJSAX",
	"LKpT41ra3YPOxKIqWoTjuDa9kVxgqakcZpwDlXGOuL37B5HZR+rBl/qNL2+XKLQujdUhMdY7lrcgUeMc",
	"WPwVU6K42YgYBbU8JIwDonBbh6Wv412XOndgcZeYnbjsXKt4KI1f9B9aXUeqxawT6m1i2KB2r/XzLaxj",
	"+QZu293hciWstmQ3kv44n1Rb7bvmy6v9zJz9ZCGNpIuiu3o9IHTOqrU6gtRVbeKnN/J3C59Ttuq9+o3h",
	"fNw170ER33PA68DXChYFoj1E2hh73S5sX/Cak6/HLXftue7Galefkf7gYtd5GeVn1rpFs+eUuqm5MLyx",
	"1LVDH1TptsizsdC115kVfYtj+j7Ld+3NlkeJ625Vbs3OnQqDxn3vn1/jNiPmEEMb2ZVPeha4zoTeX33r",
	"vAmzY8quvQNw73u/bBOArtvFHRWy43oT0IfWxy6q25bHDfB2rI4dKf+mxXH/8NXnxFaVcef02HNhXIXq",
	"p9bFzSm3ryrJhXBFVbxd0HrWxJXe/ZTE1aWsTXF81NXxIZHeeznsYL6pGl4Vc2EqV8K2KILrW+2qBDbF",
	"0tm5roAH5Uc05YwlUyQWLIsjVfwBkQvgaKrlTFVymRo503Xl7eTs3NtbxVkat6+C0y+Y0Kj7mDnAI5RI",
	"gmPyzd7wKvT3qlVdoJ8UI91KtfTGLVRXLaDKpC7JQd6MYrscZXHcEYa1noeMSkIz5TdnyWrHV5nV3+Ea",
	"k0crqVxcI8OJvkM3rcZMEdyFkOqrn+Zyo70+Jzkm2hkRY7FA09EUDRBGt4wvMVczUwUrwXckId8U+ZIU",
	"SxKQmMh8A6MP/6S0G+GVpP3pQbPUP/xZ3NfslkR9XN1lHnN2K4BX/bQYI8rQtHYYP0XmrL68Pfp3pI/y",
	"BaJwAxwRiv756R8CPYnZXPhoQYRkPPeRPrsGLp7a/G5rYKWBJzheocU8aQAbI+OAimDI2JIAYjTOx4hj",
	"GrHE16XmAtNILPASfPT///t/6PkBEj4Kinhlyr3/Qv8UwAev5kClf0kRmr6TMj2ncT710VRxZEIkvJxI",
	"TkI59ZEIWWpmib7s++rj2V8ESrFcKOPkAugYsRTMlozdgtGI/l1/UxqEQsw50UUpWPuVAKE4mWKp+h87",
	"mxBnTOqXOEgIfxFoMnmHJPCEUByjmM0J7WDYmRAZTBz1FybaLcIddSQIg6s+si53l6YTkIMTbWcRjaGp",
	"PZ73rz1qb8geHW7RVzRfYKxTXnurCj/HYUuP9Xne9z5DILr3ZXKxXFuhUgB9mJ/GOEe/T96riEZdZeXv",
	"Ynliftq9i2u9RryvlroARznQgcDou22yIohBdtxF/8DkZhBO9eAKh0ZxXZdYSDEvt3T8FZgNf/6lebvq",
	"6uHd849F2rkYpeGoX4n6cqU8MO9wGbgyHntjb3RzOLKtz3WQmR1Uq6L9Upiuz/XCmmCK52o5cbo6X2Wa",
	"W4hj/RqAWbbVI2r1KHaR7aayWVeqWNR3r1T300O1e86yhW67kDnXwuqnw23tBcw6PxsjOv1pdR/lmlcp",
	"60oUe9RYJKdKYUe66qWvnD9K7KfXk4tZFttbPFZynYFtoebClL6kh09hpmszRpGZYp9g9vJyw1/muPTQ",
	"yBRZDabYd4j2qnClsj0qqk5+urTV/kDLflWuVrdHVe77T10KG2+A9ZrjzlrgsK6cqle+dzeQeP6Wsyw1",
	"Ocs+9pt9ZN1Gg9/IO37X0ZzfzA9+zYQr5UhBF6cgWHdg43fXEM2MXgme2L8j0OFM4UTN+PKD13gr7er+",
	"6v5fAQAA///y7u4Tek8AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
